### ISSUE TITLE
ImportError: /opt/conda/envs/lgm/lib/python3.8/site-packages/diff_gaussian_rasterization/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by Ysz2022** [3DTopia/LGM#7]
When I tried to run "python app.py big --resume pretrained/model_fp16.safetensors", I got this bug:

Traceback (most recent call last):
  File "app.py", line 19, in <module>
    from core.models import LGM
  File "/userhome/LGM-main/core/models.py", line 11, in <module>
    from core.gs import GaussianRenderer
  File "/userhome/LGM-main/core/gs.py", line 7, in <module>
    from diff_gaussian_rasterization import (
  File "/opt/conda/envs/lgm/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /opt/conda/envs/lgm/lib/python3.8/site-packages/diff_gaussian_rasterization/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEESt8optionalINS2_10ScalarTypeEES6_INS2_6LayoutEES6_INS2_6DeviceEES6_IbES6_INS2_12MemoryFormatEE

Could you please tell me how to fix it?

**Comment by ashawkey** [comment]
@Ysz2022  Hi, could you try to re-install the `diff-gaussian-rasterization` package and check the logs?

**Comment by Ysz2022** [comment]
Thanks!! This work is really excellent!!
